package com.ashutosh.employee_todo_project.model;

public enum Department {

	 FINANCE, HUMAN_RESOURCES, MARKETING, RESEARCH_AND_DEVELOPMENT, IT, 
	    CUSTOMER_SERVICE, OPERATIONS_MANAGEMENT, ADMINISTRATION, PURCHASING, 
	    PRODUCTION, SALES, ACCOUNTING, MAINTENANCE, DESIGN, QUALITY_MANAGEMENT, 
	    BUSINESS_DEVELOPMENT, LAW, PRODUCT_DEVELOPMENT, HUMAN_RESOURCE_DEVELOPMENT, 
	    DISTRIBUTION, DISPATCH, STORE, MANAGEMENT
}
